name: Build and Deploy nw
on:
  push:
    branches:
      - master

env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}      
  RESOURCE_DIR: functions
jobs: 
  build-deploy:
    name: Build deploy hosting and firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: verify folders
        run: |
          cp -R dist/* public/.
          pwd
          echo "public"
          ls public
          pwd
          echo "dist"
          ls dist
          
      - name: Install Dependencies
        run: npm ci --no-audit
        working-directory: ${{ env.RESOURCE_DIR }}

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: lib
          path: ${{ env.RESOURCE_DIR }}/lib
          
      - name: Deploy Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --force

  
        
